/*******************************************************************************
 * Copyright (c) 2015 btows.com.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.cleanwiz.applock.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table lookMyPrivate.
 */
public class LookMyPrivate {

    private Long id;
    private Boolean isReaded;
    private java.util.Date lookDate;
    private String picPath;
    private String resolver;

    public LookMyPrivate() {
    }

    public LookMyPrivate(Long id) {
        this.id = id;
    }

    public LookMyPrivate(Long id, Boolean isReaded, java.util.Date lookDate, String picPath, String resolver) {
        this.id = id;
        this.isReaded = isReaded;
        this.lookDate = lookDate;
        this.picPath = picPath;
        this.resolver = resolver;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsReaded() {
        return isReaded;
    }

    public void setIsReaded(Boolean isReaded) {
        this.isReaded = isReaded;
    }

    public java.util.Date getLookDate() {
        return lookDate;
    }

    public void setLookDate(java.util.Date lookDate) {
        this.lookDate = lookDate;
    }

    public String getPicPath() {
        return picPath;
    }

    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }

    public String getResolver() {
        return resolver;
    }

    public void setResolver(String resolver) {
        this.resolver = resolver;
    }

}
