/*******************************************************************************
 * Copyright (c) 2015 btows.com.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.cleanwiz.applock.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TimeManager.
 */
public class TimeManagerInfo {

    private Long id;
    private Boolean timeIsOn;
    private String timeName;
    private Boolean isRepeact;
    private String repeactDetail;
    private Long startTime;
    private Long endTime;

    public TimeManagerInfo() {
    }

    public TimeManagerInfo(Long id) {
        this.id = id;
    }

    public TimeManagerInfo(Long id, Boolean timeIsOn, String timeName, Boolean isRepeact, String repeactDetail, Long startTime, Long endTime) {
        this.id = id;
        this.timeIsOn = timeIsOn;
        this.timeName = timeName;
        this.isRepeact = isRepeact;
        this.repeactDetail = repeactDetail;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getTimeIsOn() {
        return timeIsOn;
    }

    public void setTimeIsOn(Boolean timeIsOn) {
        this.timeIsOn = timeIsOn;
    }

    public String getTimeName() {
        return timeName;
    }

    public void setTimeName(String timeName) {
        this.timeName = timeName;
    }

    public Boolean getIsRepeact() {
        return isRepeact;
    }

    public void setIsRepeact(Boolean isRepeact) {
        this.isRepeact = isRepeact;
    }

    public String getRepeactDetail() {
        return repeactDetail;
    }

    public void setRepeactDetail(String repeactDetail) {
        this.repeactDetail = repeactDetail;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

}
