/*******************************************************************************
 * Copyright (c) 2015 btows.com.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.cleanwiz.applock.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TimeLock.
 */
public class TimeLockInfo {

    private Long id;
    private Integer beyondTimeManager;
    private String packageName;

    public TimeLockInfo() {
    }

    public TimeLockInfo(Long id) {
        this.id = id;
    }

    public TimeLockInfo(Long id, Integer beyondTimeManager, String packageName) {
        this.id = id;
        this.beyondTimeManager = beyondTimeManager;
        this.packageName = packageName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getBeyondTimeManager() {
        return beyondTimeManager;
    }

    public void setBeyondTimeManager(Integer beyondTimeManager) {
        this.beyondTimeManager = beyondTimeManager;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

}
