/*******************************************************************************
 * Copyright (c) 2015 btows.com.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.cleanwiz.applock.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table updateversionmanager.
 */
public class UpdateVersionManafer {

    private Long id;
    private Double versioncode;
    private String updateurl;
    private String filesize;
    private String intro;
    private Long checkdate;
    private Long lasttipdate;

    public UpdateVersionManafer() {
    }

    public UpdateVersionManafer(Long id) {
        this.id = id;
    }

    public UpdateVersionManafer(Long id, Double versioncode, String updateurl, String filesize, String intro, Long checkdate, Long lasttipdate) {
        this.id = id;
        this.versioncode = versioncode;
        this.updateurl = updateurl;
        this.filesize = filesize;
        this.intro = intro;
        this.checkdate = checkdate;
        this.lasttipdate = lasttipdate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getVersioncode() {
        return versioncode;
    }

    public void setVersioncode(Double versioncode) {
        this.versioncode = versioncode;
    }

    public String getUpdateurl() {
        return updateurl;
    }

    public void setUpdateurl(String updateurl) {
        this.updateurl = updateurl;
    }

    public String getFilesize() {
        return filesize;
    }

    public void setFilesize(String filesize) {
        this.filesize = filesize;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public Long getCheckdate() {
        return checkdate;
    }

    public void setCheckdate(Long checkdate) {
        this.checkdate = checkdate;
    }

    public Long getLasttipdate() {
        return lasttipdate;
    }

    public void setLasttipdate(Long lasttipdate) {
        this.lasttipdate = lasttipdate;
    }

}
