/*******************************************************************************
 * Copyright (c) 2015 btows.com.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.cleanwiz.applock.data.HideFileDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.cleanwiz.applock.data.HideFile;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HideFile.
*/
public class HideFileDao extends AbstractDao<HideFile, Long> {

    public static final String TABLENAME = "HideFile";

    /**
     * Properties of entity HideFile.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BeyondGroupId = new Property(1, Integer.class, "beyondGroupId", false, "BEYOND_GROUP_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property OldPathUrl = new Property(3, String.class, "oldPathUrl", false, "OLD_PATH_URL");
        public final static Property NewPathUrl = new Property(4, String.class, "newPathUrl", false, "NEW_PATH_URL");
        public final static Property MoveDate = new Property(5, Long.class, "moveDate", false, "MOVE_DATE");
    };


    public HideFileDao(DaoConfig config) {
        super(config);
    }
    
    public HideFileDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HideFile' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'BEYOND_GROUP_ID' INTEGER," + // 1: beyondGroupId
                "'NAME' TEXT," + // 2: name
                "'OLD_PATH_URL' TEXT," + // 3: oldPathUrl
                "'NEW_PATH_URL' TEXT," + // 4: newPathUrl
                "'MOVE_DATE' INTEGER);"); // 5: moveDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HideFile'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HideFile entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer beyondGroupId = entity.getBeyondGroupId();
        if (beyondGroupId != null) {
            stmt.bindLong(2, beyondGroupId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String oldPathUrl = entity.getOldPathUrl();
        if (oldPathUrl != null) {
            stmt.bindString(4, oldPathUrl);
        }
 
        String newPathUrl = entity.getNewPathUrl();
        if (newPathUrl != null) {
            stmt.bindString(5, newPathUrl);
        }
 
        Long moveDate = entity.getMoveDate();
        if (moveDate != null) {
            stmt.bindLong(6, moveDate);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HideFile readEntity(Cursor cursor, int offset) {
        HideFile entity = new HideFile( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // beyondGroupId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // oldPathUrl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // newPathUrl
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // moveDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HideFile entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBeyondGroupId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOldPathUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNewPathUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMoveDate(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(HideFile entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(HideFile entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
